<?php

echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Alpha - 2 | Assignment</title>';
echo '<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="./img/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">';
echo '<link href="./img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">';
echo '<link href="./img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">';
echo '<link href="./img/favicon/site.webmanifest" rel="manifest">';
echo '<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">';
echo '<link href="./styles/reset.css" rel="stylesheet">';
echo '<link href="./styles/assignment.css" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<h2>α.2 Ztrátová komprese textového souboru</h2>';
echo '<div class="row">';
echo '<div class="col-md-8 col-md-offset-2">';
echo '<p>';
echo '<br><br>Vytvořte program na kompresi textového souboru s příponou .txt, který na vstupu přijme libovolný';
echo 'textový';
echo 'soubor s textem v přirozeném jazyce a převede ho do jiného souboru s prokazatelně menší velikostí.';
echo '<br><br>Můžete využít různé metody komprese, například nahrazení slov zkratkami, využití databáze';
echo 'synonym, kde';
echo 'nahradíte delší výraz kratším stejného významu, nebo využijte vlastností přirozeného jazyka, kdy třeba';
echo 'spojku';
echo '"vždyť" lze nahradit spojkou "však", spojku "jenomže" za "jenže" apod.. Často se opakující slova, nebo';
echo 'lépe celá';
echo 'slovní spojení můžete také nahradit symbolem, či jiným sloven a k tomu vydat slovník v jiném odděleném';
echo 'souboru, nebo';
echo 'to můžete udělat přímo v textu tak, že například za první výskyt slova zapíšete jeho zkratku v závorce a';
echo 'všechny';
echo 'další výskyty už nahradíte jen zkratkou, například.: Školský zákon (SZ) říká, že se žáci mají učit.';
echo 'Současný SZ';
echo 'vznikl v roce 2004, ale před vznikem SZ. Doporučujeme nahrazovat taková slova, nebo slovní spojení,';
echo 'která se v textu';
echo 'opakují na základě frekvenční analýzy slov, tj. která slova se vyskytují a opakují častěji než jiná.';
echo '<br><br>Po kompresi textu vždy musíte dodržet hlavní pravidlo, ž musíte zachovat význam textu a celý';
echo 'text musí být';
echo 'stále dobře čitelný. Platí ale i další pravidla:';
echo '<br><br>Vstupem programu je jeden textový soubor.';
echo '<br><br>Výstupem programu je jeden nebo více souborů.';
echo '<br><br>Text po všech úpravách musí být čitelný člověkem a jeho význam musí být zachován i po změně nebo';
echo 'odstranění a';
echo 'nahrazení slov. Tedy text se může změnit, například odstraněním nepotřebných slov a nic neříkajících';
echo 'vět, ale nesmí';
echo 'to ovlivnit to, co je v textu zásadní.';
echo '<br><br>Program musí být konfigurovatelný například, jaky soubor míá načítat kam má uložit výsledek a';
echo 'jak ho';
echo 'má';
echo 'pojmenovat.';
echo '<br><br>Program musí informaci o každé úpravě textu vytvořit záznam v logu, kde bude informace o tom v';
echo 'jaké';
echo 'konfiguraci';
echo 'se program nacházel a co kdy zpracoval a zda-li a jak dobře se povedlo komprimovat nebo dekomprimovat,';
echo 'nebo zda-li';
echo 'nastala chyba.';
echo '<br><br>Program musí umět vypsat informace o svých operacích z logu a musí je umožnit filtrovat podle';
echo 'zadaného času';
echo 'dalších parametrů, které zvolíte.';
echo '<br><br>Program musí umět poskytnout uživateli nápovědu o tom jak se používá.';
echo '<br> <br>Program nesmí používat žádnou externí knihovnu pro komprese nebo dekomprese.';
echo '<br><br>Program se musí umět vypořádat s chybami typu, že soubor nelze číst kvůli oprávnění, že soubor';
echo 'není';
echo 'textový';
echo 'apod. O každé chybě musí být záznam v logu a také se musí uživateli zobrazit vhodná chybová hláška.';
echo '<br><br>Program musí obsahovat unit testy s ukázkami jednotlivých funkcí.';
echo '<br><br>Program musí být rozdělen do více souborů a složek pro jednotlivé části. Logy by měly být ve';
echo 'složce';
echo '/log,';
echo 'konfigurace ve složce /config, data a soubory ve složce /data, zdrojový kód pak musí být rozdělen do';
echo 'dalších';
echo 'package/modulů ve složce /src (uživatelské rozhraní zvlášť, algoritmy pro kompresi zvlášť, práce s logem';
echo 'zvlášť).';
echo 'Dokumentace ve složce /doc a unit testy ve složce /test. Pokud použijete cizí zdrojový kód musí byt také';
echo 've zvláštní';
echo 'složce, například /lib nebo /vendor.';
echo '<br><br>Program může kromě komprimovaného souboru generovat i pomocné soubory, například s kódovací';
echo 'tabulkou, seznam';
echo 'zkratek apod.';
echo '<br><br><br>Doporučujeme také využít OOP a návrhových vzorů a znalostí z kapitol 1 až 13 a dávat pozor';
echo 'především';
echo 'na všechny';
echo 'možné chybové stavy.';
echo '<br><br>Kritéria hodnocení:';
echo '<br>Program musí splňovat výše uvedená kritéria.';
echo '<br><br>Program musí mít celé UI a nápovědu ve stejném jazyce, ve kterém umí komprimovat text a musí být';
echo 'jasné, o jaký';
echo 'jazyk jde. Povolené jsou pouze jazyky, které jsou v naší škole vyučovány.';
echo '<br><br>Program musí být spustitelný bez vývojového prostředí (tj.nebude spouštěn v PyCharm ani VStudio)';
echo 'na';
echo 'školním PC.';
echo 'Nelze tedy použít technologie a knihovny, které nelze ve škole instalovat/nasadit.';
echo '<br><br>Při splnění všech výše uvedených pravidel bude práce hodnocena na stupnici 1 az 5 podle kriterii';
echo 'kvality,';
echo 'pri nesplnění jediného z nich , nebo podvodu bude hodnocena znamkou 5, bez vyhodnoceni kritérií kvality.';
echo '<br><br><br>Rozšíření pro pokročilé:';
echo '<br>V této úloze můžete také využít nějaké kódování symbolů/znaků nebo celých slovních spojení do';
echo 'binární podoby,';
echo 'ale k tomu pak musíte vytvořit program, který umí takový soubor načíst a zobrazit tak, aby byl čitelný';
echo 'pro člověka.';
echo 'Pokud tuto cestu zvolíte, tak z důvodu návaznosti na jiné úlohy zde explicitně zakazujeme jakékoliv';
echo 'použití';
echo 'Huffmanova kódování. To v této úloze použít nesmíte a to ani, když ho implementujete vlastním způsobem.';
echo '<br><br><br><br><br>Naposledy změněno: Pátek, 22. prosince 2023, 11.08';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="row btn-container">';
echo '<div class="col-md-2 col-md-offset-5">';
echo '<a class="btn btn-primary" href="./">Back</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';