<?php
session_start();
if (!isset($_SESSION['email'])) {
    header("Location: ../");
    exit();
}
include '../templates/assignment.php';
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>EstateAtlas | Assignment</title>';
echo '<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="img/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">';
echo '<link href="img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">';
echo '<link href="img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">';
echo '<link href="img/favicon/site.webmanifest" rel="manifest">';
echo '<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">';
echo '<link href="styles/reset.css" rel="stylesheet">';
echo '<link href="styles/assignment.css" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<h2>α.3 Databázový systém</h2>';
echo '<div class="row">';
echo '<div class="col-md-8 col-md-offset-2">';
echo '<ul style="list-style-type:circle">';
echo '<p>Vytvořte uživatelské rozhraní a databázi pro libovolnou činnost, která spadá do oblasti státní správy ČR dle seznamu: <a href="https://archi.gov.cz/znalostni_baze:seznam_agend" target="_blank">https://archi.gov.cz/znalostni_baze:seznam_agend</a>. Databáze musí mít alespoň 6 tabulek. V rámci databáze musí být min. jedna vazbu M:N a min. dva databázové pohledy (view). Mezi atributy musíte použít následující datové typy: Reálné číslo (float), Logická hodnota (bool), Výčet (enum), Řetězec (string), Datum a čas (datetime).</p>';
echo '<p>Uživatelské rozhraní nebo API musí umožňovat:</p>';
echo '<ul>';
echo '<li>Vložení, smazání a úpravu nějaké informace, záznamu, který se ukládá do více než jedné tabulky. Například vložení objednávky, která má položky apod.</li>';
echo '<li>Provést transakci nad více než jednou tabulkou. Například převod kreditních bodů mezi dvěma účty apod.</li>';
echo '<li>Vygenerovat souhrný report, který bude obsahovat smysluplná agregovaná data z alespoň tří tabulek Vaší databáze, např. počet součty nákupů podle měst apod. Report musí mít hlavičku a patičku.</li>';
echo '<li>Import dat do min. dvou tabulek z formátu CSV, XML nebo JSON.</li>';
echo '<li>Nastavit celý program v konfiguračním souboru.</li>';
echo '</ul>';
echo '<p>K programu zpracujte a odevzdejte:</p>';
echo '<ul>';
echo '<li>Testovací scénář ve formátu PDF (.pdf) pro spuštění aplikace, včetně nastavení a importu databázové struktury.</li>';
echo '<li>Min. tři další testovací scénáře ve formátu PDF (.pdf) podle kterých můžeme otestovat všechny výše uvedné body, včetně všech druhů chyb a možností konfigurace.</li>';
echo '<li>Řádnou dokumentaci, která bude obsahovat vše z Příloha 1 - Checklist v českém nebo anglickém jazyce.</li>';
echo '<li>V případě všech možných chyb musí program rozumným způsobem reagovat, nebo vyžadovat součinnost uživatele k vyřešení problému. To je třeba podchytit v testovacích scénářích.</li>';
echo '<li>Program musí využívat návrhové vzory a "best practice" tam, kde je to vhodné.</li>';
echo '</ul>';
echo '<p>Program nemusí obsahovat unit testy, na místo toho musí obsahovat testovací scénáře pro testery. Tester je člověk, který bude aplikaci testovat. Kontrolovat a hodnotit se pak bude jen dle scénářů a dle dokumentace. Pokud budou dokumentace i testovací scénář správně zpracovány bude nahlíženo i do zdrojového kódu. Práce, které nebudou obsahovat scénáře a dokumentaci, nebo tyto dvě části nebudou zpracovány v dostatečné kvalitě budou hodnoceny známkou nedostatečně bez kontroly zdrojového kódu.</p>';
echo '<p>Naposledy změněno: Pondělí, 22. ledna 2024, 16.31</p>';
echo '<p>Vybrané téma: A124 | Katastr nemovitostí</p>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="row btn-container">';
echo '<div class="col-md-2 col-md-offset-5">';
echo '<a class="btn btn-primary" href="./">Back</a>';
echo '<button id="switch" class="btn btn-secondary" onclick="cycleThemes()" type="button">Switch</button>';
echo '</div>';
echo '<script src="../scripts/dark-mode.js"></script>';
echo '</body>';
echo '</html>';