<?php
session_start();
if (!isset($_SESSION['email'])) {
    header("Location: ../");
    exit();
}
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>EstateAtlas | Write</title>';
echo '<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="img/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">';
echo '<link href="img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">';
echo '<link href="img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">';
echo '<link href="img/favicon/site.webmanifest" rel="manifest">';
echo '<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">';
echo '<link href="styles/reset.css" rel="stylesheet">';
echo '<link href="styles/index.css" rel="stylesheet">';
echo '<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"';
echo 'rel="stylesheet"/>';
echo '<link href="styles/google_icons.css" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '<div class="container" style="height: 89vh;">';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<a class="btn btn-warning btn-lg btn-block" href="files.php" role="button">';
echo '<i class="bi bi-file-earmark" style="font-size: 250px;"></i><br>Files</a>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<a class="btn btn-warning btn-lg btn-block" href="manually.php" role="button">';
echo '<i class="bi bi-pencil-square" style="font-size:250px;"></i><br>Manually';
echo '</a>';
echo '</div>';
echo '</div>';
echo '<div class="row" style="margin-top: 30px;">';
echo '<div class="col-md-10">';
echo '<a class="btn btn-danger btn-lg btn-block" href="./" role="button"';
echo 'style="height: 100px; display: flex; align-items: center; justify-content: center;">';
echo '<i class="bi bi-arrow-left m-2" style="font-size:55px;"></i>Return';
echo '</a>';
echo '</div>';
echo '<div class="col-md-2">';
echo '<button id="switch" class="btn btn-lg btn-secondary btn-block" onclick="cycleThemes()" style="font-size:55px;" type="button">Switch</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<script src="../scripts/dark-mode.js"></script>';
echo '</body>';
echo '</html>';
